/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.noppapeli;




/**
 *
 * @author heyno
 */
public class Noppapeli1 extends javax.swing.JFrame {


    /**
     * Creates new form Noppapeli1
     */
    public Noppapeli1() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jColorChooser3 = new javax.swing.JColorChooser();
        jColorChooser4 = new javax.swing.JColorChooser();
        jLabel1 = new javax.swing.JLabel();
        jtxtLukupelaaja = new javax.swing.JTextField();
        jbtnStart = new javax.swing.JButton();
        jbtnStop = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtxtLukukone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtResult = new javax.swing.JTextArea();
        jtxtTulosPel = new javax.swing.JTextField();
        jtxtTulosKone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\heyno\\Desktop\\dice_PNG63.png")); // NOI18N

        jtxtLukupelaaja.setFont(new java.awt.Font("Showcard Gothic", 1, 60)); // NOI18N
        jtxtLukupelaaja.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtLukupelaaja.setText("0");
        jtxtLukupelaaja.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtxtLukupelaaja.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtLukupelaaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLukupelaajaActionPerformed(evt);
            }
        });

        jbtnStart.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jbtnStart.setText("heitä noppaa");
        jbtnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnStartActionPerformed(evt);
            }
        });

        jbtnStop.setBackground(new java.awt.Color(247, 247, 247));
        jbtnStop.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jbtnStop.setForeground(new java.awt.Color(176, 0, 0));
        jbtnStop.setText("lopettaa");
        jbtnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnStopActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("tulos");

        jtxtLukukone.setFont(new java.awt.Font("Showcard Gothic", 1, 60)); // NOI18N
        jtxtLukukone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtLukukone.setText("0");
        jtxtLukukone.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtxtLukukone.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtLukukone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLukukoneActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("pelaaja");

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("kone");

        jtxtResult.setColumns(20);
        jtxtResult.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jtxtResult.setRows(5);
        jScrollPane1.setViewportView(jtxtResult);

        jtxtTulosPel.setText("0");

        jtxtTulosKone.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jbtnStart))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jbtnStop)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtLukupelaaja, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(123, 123, 123)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtLukukone, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jtxtTulosPel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtTulosKone, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtTulosPel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtTulosKone, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtLukupelaaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtLukukone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jbtnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnStop)))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnStartActionPerformed
        // TODO add your handling code here:
        noppa1 kone1 = new noppa1(6);
        noppa1 kone2 = new noppa1(6);
        noppa1 pelaaja1 = new noppa1(6);
        noppa1 pelaaja2 = new noppa1(6);
        int koneSumma = Integer.parseInt(jtxtLukukone.getText());
        int pelaajaSumma = Integer.parseInt(jtxtLukupelaaja.getText());

        String tulos;
        int pelaatulos = Integer.parseInt(jtxtTulosPel.getText());
        int konetulos = Integer.parseInt(jtxtTulosKone.getText());
        
            if (koneSumma == 0 || ((koneSumma < 21) && (koneSumma < pelaajaSumma))) {
             
            }
            
            kone1.heita();
            kone2.heita();
            koneSumma += kone1.getArvo() + kone2.getArvo(); 
            
            pelaaja1.heita();
            pelaaja2.heita();
            pelaajaSumma += pelaaja1.getArvo() + pelaaja2.getArvo();
            
            String appendText = ("Koneella on " + koneSumma + " pistettä " + "\n" + "Pelaajalla on " + pelaajaSumma + " pistettä" + "\n" + "\n");
            jtxtResult.append(appendText);
            jtxtLukupelaaja.setText(String.valueOf(pelaajaSumma));
            jtxtLukukone.setText(String.valueOf(koneSumma));
       
            if ((koneSumma > 21) || (pelaajaSumma > 21)) {
                tulos = ("Molemmat hävisivät.\n");
                jtxtTulosPel.setText(String.valueOf(pelaatulos));
                jtxtTulosKone.setText(String.valueOf(konetulos));
                jtxtResult.append(tulos);
            
            } else if ((koneSumma > 21) && (pelaajaSumma <= 21)) {
                tulos = ("Pelaaja voitti!!\n");
                pelaatulos +=1;
                jtxtTulosPel.setText(String.valueOf(pelaatulos));
                jtxtResult.append(tulos);
                
            } else if ((koneSumma <= 21) && (pelaajaSumma > 21)) {
                tulos = ("Kone voitti!!\n");
                konetulos +=1;
                jtxtTulosKone.setText(String.valueOf(konetulos));
                jtxtResult.append(tulos);
                
            } else if (koneSumma >= pelaajaSumma && pelaajaSumma > 21) {
                tulos = ("Pelaaja voitti!!\n");
                konetulos +=1;
                jtxtTulosKone.setText(String.valueOf(konetulos));
                jtxtResult.append(tulos);
               
            } else if (koneSumma == 21 && pelaajaSumma == 21) {
                tulos = ("Tasapeli\n");
                konetulos +=1;
                jtxtTulosKone.setText(String.valueOf(konetulos));
                jtxtResult.append(tulos);
      
            
            } else {
                tulos = ( "");
                jtxtResult.append(tulos); 
            }
            if (pelaajaSumma > 21 || koneSumma > 21) {
                pelaajaSumma = 0;
                koneSumma = 0;
                jtxtLukupelaaja.setText(String.valueOf(pelaajaSumma));
                jtxtLukukone.setText(String.valueOf(koneSumma));
                
            
            
           }
            

        
    }//GEN-LAST:event_jbtnStartActionPerformed

    private void jtxtLukupelaajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLukupelaajaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jtxtLukupelaajaActionPerformed

    private void jtxtLukukoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLukukoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLukukoneActionPerformed

    private void jbtnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnStopActionPerformed
        // TODO add your handling code here:
        noppa1 kone1 = new noppa1(6);
        noppa1 kone2 = new noppa1(6);
        int pelaatulos = Integer.parseInt(jtxtTulosPel.getText());
        int konetulos = Integer.parseInt(jtxtTulosKone.getText());
        int koneSumma = Integer.parseInt(jtxtLukukone.getText());
        int pelaajaSumma = Integer.parseInt(jtxtLukupelaaja.getText());
        String tulos;

            if (koneSumma == 0 || ((koneSumma < 21) && (koneSumma < pelaajaSumma))) {
                kone1.heita();
                kone2.heita();
                koneSumma += kone1.getArvo() + kone2.getArvo();                  
            
            }
            
            String appendText = ("Koneella on " + koneSumma + " pistettä " + "\n" + "Pelaajalla on " + pelaajaSumma + " pistettä" + "\n" + "\n");
            jtxtResult.append(appendText);
            jtxtLukupelaaja.setText(String.valueOf(pelaajaSumma));
            jtxtLukukone.setText(String.valueOf(koneSumma));
           
            if ((koneSumma > 21) && (pelaajaSumma <= 21)) {
                tulos = ("Pelaaja voitti!!\n");
                pelaatulos +=1;
                pelaajaSumma = 0;
                koneSumma = 0;
                jtxtLukupelaaja.setText(String.valueOf(pelaatulos));
                jtxtLukukone.setText(String.valueOf(koneSumma));
                jtxtResult.append(tulos);               
                jtxtTulosPel.setText(String.valueOf(pelaajaSumma));
                jtxtTulosKone.setText(String.valueOf(koneSumma));

                
            } else if ((koneSumma <= 21) && (pelaajaSumma > 21)) {
                tulos = ("Kone voitti!!\n");
                konetulos +=1;
                jtxtLukukone.setText(String.valueOf(konetulos));
                jtxtResult.append(tulos);
                pelaajaSumma = 0;
                koneSumma = 0;
                jtxtLukupelaaja.setText(String.valueOf(pelaajaSumma));
                jtxtTulosPel.setText(String.valueOf(pelaajaSumma));
                jtxtTulosKone.setText(String.valueOf(koneSumma));
                
            } else if (koneSumma > pelaajaSumma && pelaajaSumma < 21) {
                tulos = ("Kone voitti!!\n");
                konetulos +=1;
                jtxtLukukone.setText(String.valueOf(konetulos));
                jtxtResult.append(tulos);
                pelaajaSumma = 0;
                koneSumma = 0;
                jtxtLukupelaaja.setText(String.valueOf(pelaajaSumma));
                jtxtTulosPel.setText(String.valueOf(pelaajaSumma));
                jtxtTulosKone.setText(String.valueOf(koneSumma));
               
            } else if (koneSumma == pelaajaSumma && pelaajaSumma < 21) {
                tulos = ("Tasapeli\n");
                jtxtResult.append(tulos);                  
                konetulos +=1;
                pelaajaSumma = 0;
                koneSumma = 0;   
                jtxtLukukone.setText(String.valueOf(koneSumma));
                jtxtLukupelaaja.setText(String.valueOf(pelaajaSumma));
                jtxtTulosPel.setText(String.valueOf(pelaajaSumma));
                jtxtTulosKone.setText(String.valueOf(koneSumma));
      
            if (pelaajaSumma == 21) {
                tulos = ("Pelaaja voitti!!\n");
                jtxtResult.append(tulos);                
                pelaatulos +=1;
                jtxtLukupelaaja.setText(String.valueOf(pelaatulos));                
                pelaajaSumma = 0;
                koneSumma = 0;
                jtxtLukukone.setText(String.valueOf(koneSumma));
                jtxtTulosPel.setText(String.valueOf(pelaajaSumma));
                jtxtTulosKone.setText(String.valueOf(koneSumma));            
            } 
            
            if (koneSumma == 21) {
                tulos = ("Kone voitti!!\n");               
                konetulos +=1;
                jtxtLukukone.setText(String.valueOf(konetulos)); 
                jtxtResult.append(tulos);                
                pelaajaSumma = 0;
                koneSumma = 0;   
                jtxtLukupelaaja.setText(String.valueOf(pelaajaSumma));
                jtxtTulosPel.setText(String.valueOf(pelaajaSumma));
                jtxtTulosKone.setText(String.valueOf(koneSumma));            
            }else {
                tulos = ( "");
                jtxtResult.append(tulos); 
            }
            }
            
    }//GEN-LAST:event_jbtnStopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Noppapeli1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Noppapeli1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Noppapeli1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Noppapeli1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Noppapeli1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JColorChooser jColorChooser3;
    private javax.swing.JColorChooser jColorChooser4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnStart;
    private javax.swing.JButton jbtnStop;
    private javax.swing.JTextField jtxtLukukone;
    private javax.swing.JTextField jtxtLukupelaaja;
    private javax.swing.JTextArea jtxtResult;
    private javax.swing.JTextField jtxtTulosKone;
    private javax.swing.JTextField jtxtTulosPel;
    // End of variables declaration//GEN-END:variables
}
