/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parturikampaaja;

import javax.swing.DefaultListModel;

/**
 *
 * @author heyno
 */
public class parturikampaaja1 extends javax.swing.JFrame {

    /**
     * Creates new form parturikampaaja1
     */
    public parturikampaaja1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jrbtAikuiset = new javax.swing.JRadioButton();
        jrbtLapset = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jrbtLyhyet = new javax.swing.JRadioButton();
        jrbtKeski = new javax.swing.JRadioButton();
        jrbtPitkat = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jtxtMaara = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtNimi = new javax.swing.JTextField();
        jchkRaidat = new javax.swing.JCheckBox();
        jchkLabeltyy = new javax.swing.JCheckBox();
        jchkKoko = new javax.swing.JCheckBox();
        jchkjuhla = new javax.swing.JCheckBox();
        jchkKoe = new javax.swing.JCheckBox();
        jchkPesu = new javax.swing.JCheckBox();
        jchkKihar = new javax.swing.JCheckBox();
        jchkPerman = new javax.swing.JCheckBox();
        jchkAle = new javax.swing.JCheckBox();
        jlplpic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jButton1.setText("GET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jButton2.setText("ADD =>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbtAikuiset);
        jrbtAikuiset.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jrbtAikuiset.setText("aikuiset 25 eur");
        jrbtAikuiset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtAikuisetActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbtLapset);
        jrbtLapset.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jrbtLapset.setText("lapset 15 eur");
        jrbtLapset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtLapsetActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(176, 11, 141));
        jLabel1.setText("Parturi-kampaamo");

        buttonGroup2.add(jrbtLyhyet);
        jrbtLyhyet.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jrbtLyhyet.setText("lyhyet 0 eur ");
        jrbtLyhyet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtLyhyetActionPerformed(evt);
            }
        });

        buttonGroup2.add(jrbtKeski);
        jrbtKeski.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jrbtKeski.setText("keskipitkät 5 eur");

        buttonGroup2.add(jrbtPitkat);
        jrbtPitkat.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jrbtPitkat.setText("pitkät 10 eur");

        jList1.setBackground(new java.awt.Color(244, 192, 227));
        jList1.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jScrollPane1.setViewportView(jList1);

        jList2.setBackground(new java.awt.Color(244, 192, 227));
        jList2.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jScrollPane2.setViewportView(jList2);

        jLabel2.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jLabel2.setText("Henkilömäärä");

        jLabel3.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jLabel3.setText("Nimi, sukunimi");

        jchkRaidat.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jchkRaidat.setText("raidat 30 eur");

        jchkLabeltyy.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jchkLabeltyy.setText("label\ttyviväri 30 eur");

        jchkKoko.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jchkKoko.setText("koko pään(=hiusten:)  värjäys 80 eur");

        jchkjuhla.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jchkjuhla.setText(" juhlakampaus 50 eur");

        jchkKoe.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jchkKoe.setText("koekampaus 20 eur");

        jchkPesu.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jchkPesu.setText("pesu 10 eur");

        jchkKihar.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jchkKihar.setText("kiharrus 15 eur");

        jchkPerman.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jchkPerman.setText("permanentti 50 eur");

        jchkAle.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jchkAle.setForeground(new java.awt.Color(153, 0, 102));
        jchkAle.setText("Internet-varauksella saa - 5 eur alennuksen, jos kokonaissumma on 25 eur tai enemmän.");

        jlplpic.setIcon(new javax.swing.ImageIcon("C:\\Users\\heyno\\Documents\\NetBeansProjects\\parturikampaaja\\src\\main\\java\\com\\mycompany\\parturikampaaja\\mal2.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jchkAle, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jlplpic, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jrbtAikuiset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbtLapset, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtMaara, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtNimi, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(102, 102, 102)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jchkKoko, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jchkKihar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jchkPerman, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jchkLabeltyy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jchkRaidat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jchkjuhla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jchkKoe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jchkPesu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrbtLyhyet, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbtKeski)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbtPitkat)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(154, 154, 154))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jtxtNimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jtxtMaara)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlplpic, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbtAikuiset)
                            .addComponent(jrbtLapset))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbtLyhyet)
                            .addComponent(jrbtKeski)
                            .addComponent(jrbtPitkat))
                        .addGap(18, 18, 18)
                        .addComponent(jchkRaidat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jchkLabeltyy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jchkKoko)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jchkjuhla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jchkKoe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jchkPesu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jchkKihar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jchkPerman))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(28, 28, 28)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jchkAle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultListModel dlm = new DefaultListModel();
        
        int maara = 0;
        double total;
        double i;
        double hinta;
        int a;
        String nimi = jtxtNimi.getText();

        maara = Integer.parseInt(jtxtMaara.getText());

        
        jrbtAikuiset.setActionCommand("Aikuiset");
        jrbtLapset.setActionCommand("Lapset");
        
        jrbtLyhyet.setActionCommand("Lyhyet");
        jrbtKeski.setActionCommand("Keski");
        jrbtPitkat.setActionCommand("Pitkät");
        

        if(buttonGroup1.getSelection().getActionCommand()=="Aikuiset") {
            a = 25;
                if(buttonGroup2.getSelection().getActionCommand()=="Keski"){
                    i = a + 5;
                    if(jchkRaidat.isSelected()){
                        i += 30; 
                    }
                    if(jchkLabeltyy.isSelected()){
                        i += 30;     
                    }
                    if(jchkKoko.isSelected()){
                        i += 80;                          
                    }
                    if(jchkjuhla.isSelected()){
                        i += 50;
                    }
                    if(jchkKoe.isSelected()){
                        i += 20;                          
                    }
                    if(jchkPesu.isSelected()){
                        i += 10;                          
                    }
                    if(jchkKihar.isSelected()){
                        i += 15;                          
                    }
                    if(jchkPerman.isSelected()){
                        i += 50;                         
                    }
                
                    total = maara * i;
                    if(jchkAle.isSelected()){
                        if(total >= 25) {
                            total = total - 5;
                        }  
                    }
                    dlm.addElement("Nimi: " + nimi + "; Henkilömäärä: " + maara + "; Loppusumma: " + total + " €"); 
                }
                if(buttonGroup2.getSelection().getActionCommand()=="Pitkät"){
                    i = a + 10;
                    if(jchkRaidat.isSelected()){
                        i += 30; 
                    }
                    if(jchkLabeltyy.isSelected()){
                        i += 30;     
                    }
                    if(jchkKoko.isSelected()){
                        i += 80;                          
                    }
                    if(jchkjuhla.isSelected()){
                        i += 50;
                    }
                    if(jchkKoe.isSelected()){
                        i += 20;                          
                    }
                    if(jchkPesu.isSelected()){
                        i += 10;                          
                    }
                    if(jchkKihar.isSelected()){
                        i += 15;                          
                    }
                    if(jchkPerman.isSelected()){
                        i += 50;                         
                    }
                
                    total = maara * i;
                    if(jchkAle.isSelected()){
                        if(total >= 25) {
                            total = total - 5;
                        }  
                    }
                    dlm.addElement("Nimi: " + nimi + "; Henkilömäärä: " + maara + "; Loppusumma: " + total + " €"); 
                }
                if(buttonGroup2.getSelection().getActionCommand()=="Lyhyet"){
                    i = a + 0;                
                    if(jchkRaidat.isSelected()){
                        i += 30; 
                    }
                    if(jchkLabeltyy.isSelected()){
                        i += 30;     
                    }
                    if(jchkKoko.isSelected()){
                        i += 80;                          
                    }
                    if(jchkjuhla.isSelected()){
                        i += 50;
                    }
                    if(jchkKoe.isSelected()){
                        i += 20;                          
                    }
                    if(jchkPesu.isSelected()){
                        i += 10;                          
                    }
                    if(jchkKihar.isSelected()){
                        i += 15;                          
                    }
                    if(jchkPerman.isSelected()){
                        i += 50;                         
                    }
                
                    total = maara * i;
                    if(jchkAle.isSelected()){
                        if(total >= 25) {
                            total = total - 5;
                        }  
                    }
                    dlm.addElement("Nimi: " + nimi + "; Henkilömäärä: " + maara + "; Loppusumma: " + total + " €"); 
                }
             
        }
        
        jList1.setModel(dlm);               
        
        
        if(buttonGroup1.getSelection().getActionCommand()=="Lapset") {
            a = 15;
                if(buttonGroup2.getSelection().getActionCommand()=="Keski"){
                    i = a + 5;
                    if(jchkRaidat.isSelected()){
                        i += 30; 
                    }
                    if(jchkLabeltyy.isSelected()){
                        i += 30;     
                    }
                    if(jchkKoko.isSelected()){
                        i += 80;                          
                    }
                    if(jchkjuhla.isSelected()){
                        i += 50;
                    }
                    if(jchkKoe.isSelected()){
                        i += 20;                          
                    }
                    if(jchkPesu.isSelected()){
                        i += 10;                          
                    }
                    if(jchkKihar.isSelected()){
                        i += 15;                          
                    }
                    if(jchkPerman.isSelected()){
                        i += 50;                         
                    }
                
                    total = maara * i;
                    if(jchkAle.isSelected()){
                        if(total >= 25) {
                            total = total - 5;
                        }  
                    }
                    dlm.addElement("Nimi: " + nimi + "; Henkilömäärä: " + maara + "; Loppusumma: " + total + " €"); 
                }
                if(buttonGroup2.getSelection().getActionCommand()=="Pitkät"){
                    i = a + 10;
                    if(jchkRaidat.isSelected()){
                        i += 30; 
                    }
                    if(jchkLabeltyy.isSelected()){
                        i += 30;     
                    }
                    if(jchkKoko.isSelected()){
                        i += 80;                          
                    }
                    if(jchkjuhla.isSelected()){
                        i += 50;
                    }
                    if(jchkKoe.isSelected()){
                        i += 20;                          
                    }
                    if(jchkPesu.isSelected()){
                        i += 10;                          
                    }
                    if(jchkKihar.isSelected()){
                        i += 15;                          
                    }
                    if(jchkPerman.isSelected()){
                        i += 50;                         
                    }
                
                    total = maara * i;
                    if(jchkAle.isSelected()){
                        if(total >= 25) {
                            total = total - 5;
                        }  
                    }
                    dlm.addElement("Nimi: " + nimi + "; Henkilömäärä: " + maara + "; Loppusumma: " + total + " €"); 
                }
                if(buttonGroup2.getSelection().getActionCommand()=="Lyhyet"){
                    i = a + 0;                
                    if(jchkRaidat.isSelected()){
                        i += 30; 
                    }
                    if(jchkLabeltyy.isSelected()){
                        i += 30;     
                    }
                    if(jchkKoko.isSelected()){
                        i += 80;                          
                    }
                    if(jchkjuhla.isSelected()){
                        i += 50;
                    }
                    if(jchkKoe.isSelected()){
                        i += 20;                          
                    }
                    if(jchkPesu.isSelected()){
                        i += 10;                          
                    }
                    if(jchkKihar.isSelected()){
                        i += 15;                          
                    }
                    if(jchkPerman.isSelected()){
                        i += 50;                         
                    }
                
                    total = maara * i;
                    if(jchkAle.isSelected()){
                        if(total >= 25) {
                            total = total - 5;
                        }  
                    }
                    dlm.addElement("Nimi: " + nimi + "; Henkilömäärä: " + maara + "; Loppusumma: " + total + " €");
                }
             
       
        
        jList1.setModel(dlm);     
                       

    
        }  
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jrbtAikuisetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtAikuisetActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jrbtAikuisetActionPerformed

    private void jrbtLapsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtLapsetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbtLapsetActionPerformed

    private void jrbtLyhyetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtLyhyetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbtLyhyetActionPerformed
    DefaultListModel dlm2 = new DefaultListModel();
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        
        dlm2.addElement(jList1.getSelectedValue());
        jList2.setModel(dlm2);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(parturikampaaja1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(parturikampaaja1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(parturikampaaja1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(parturikampaaja1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new parturikampaaja1().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox jchkAle;
    private javax.swing.JCheckBox jchkKihar;
    private javax.swing.JCheckBox jchkKoe;
    private javax.swing.JCheckBox jchkKoko;
    private javax.swing.JCheckBox jchkLabeltyy;
    private javax.swing.JCheckBox jchkPerman;
    private javax.swing.JCheckBox jchkPesu;
    private javax.swing.JCheckBox jchkRaidat;
    private javax.swing.JCheckBox jchkjuhla;
    private javax.swing.JLabel jlplpic;
    private javax.swing.JRadioButton jrbtAikuiset;
    private javax.swing.JRadioButton jrbtKeski;
    private javax.swing.JRadioButton jrbtLapset;
    private javax.swing.JRadioButton jrbtLyhyet;
    private javax.swing.JRadioButton jrbtPitkat;
    private javax.swing.JTextField jtxtMaara;
    private javax.swing.JTextField jtxtNimi;
    // End of variables declaration//GEN-END:variables
}
