/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.merkkijono;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author heyno
 */
public class Merkkijono1 extends javax.swing.JFrame {
DefaultListModel dm = new DefaultListModel();
ArrayList<String> al = new ArrayList();
    /**
     * Creates new form Merkkijono1
     */
    public Merkkijono1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxt1 = new javax.swing.JTextField();
        jtxt2 = new javax.swing.JTextField();
        jrbtVertaaminen = new javax.swing.JRadioButton();
        jrbtPituus = new javax.swing.JRadioButton();
        jrbtSuuri = new javax.swing.JRadioButton();
        jrbtLiite = new javax.swing.JRadioButton();
        jrbtK = new javax.swing.JRadioButton();
        jrbtKorvaus = new javax.swing.JRadioButton();
        jrbtTaulukko = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jbtnAja = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtareaTulos = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Merkkijonon käsittelyharjoituksia:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Teksti1");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Teksti2");

        buttonGroup1.add(jrbtVertaaminen);
        jrbtVertaaminen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jrbtVertaaminen.setText("Teksti1 ja Teksti2 yhtäsuuruuden vertaaminen");

        buttonGroup1.add(jrbtPituus);
        jrbtPituus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jrbtPituus.setText("Teksti1 pituus");

        buttonGroup1.add(jrbtSuuri);
        jrbtSuuri.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jrbtSuuri.setText("Teksti2 SUUREKSI");

        buttonGroup1.add(jrbtLiite);
        jrbtLiite.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jrbtLiite.setText("Teksti1 pieneksi ja Teksti2 liitetaan perään");

        buttonGroup1.add(jrbtK);
        jrbtK.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jrbtK.setText("Teksti2: alkaako K kirjaimella?");

        buttonGroup1.add(jrbtKorvaus);
        jrbtKorvaus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jrbtKorvaus.setText("Teksti1: korvaa \"vaikea\" sanalla \"helppo\"");

        buttonGroup1.add(jrbtTaulukko);
        jrbtTaulukko.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jrbtTaulukko.setText("Teksti1: Kirjoita Opel, Volvo, BMW, Mersu ja ohjelma muuntaa merkkijonon string taulukoksi ja taulukko tulostetaan takaisin for-silmukalla Tulos-kenttaan.");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Tulos:");

        jbtnAja.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnAja.setText("Aja");
        jbtnAja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAjaActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jtxtareaTulos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbtTaulukko, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jrbtSuuri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jrbtPituus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jrbtLiite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(278, 278, 278)
                        .addComponent(jbtnAja)
                        .addGap(154, 154, 154))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrbtK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(236, 236, 236))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrbtKorvaus, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jrbtVertaaminen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(143, 143, 143))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                            .addComponent(jtxt2))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jrbtVertaaminen)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbtPituus)
                    .addComponent(jbtnAja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbtSuuri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbtLiite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbtK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbtKorvaus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbtTaulukko)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAjaActionPerformed
        // TODO add your handling code here:
        String teksti1 = jtxt1.getText();
        String teksti2 = jtxt2.getText();
        
        jrbtVertaaminen.setActionCommand("Vertaaminen");
        jrbtPituus.setActionCommand("Pituus");
        jrbtSuuri.setActionCommand("Suuri");
        jrbtLiite.setActionCommand("Liite");
        jrbtK.setActionCommand("K");
        jrbtKorvaus.setActionCommand("Korvaus");
        jrbtTaulukko.setActionCommand("Taulukko");
        
        
        if(buttonGroup1.getSelection().getActionCommand()=="Vertaaminen") {
            if(teksti1.equals(teksti2)) {
                dm.addElement("teksti1 on yhtä kuin teksti2");
            } else {
                dm.addElement("teksti1 ei ole yhtä kuin teksti2");
            }
            jtxtareaTulos.setModel(dm);
        }
        
        if(buttonGroup1.getSelection().getActionCommand()=="Pituus") {
            int pituus=0;
            for(int i = 0; i <= teksti1.length(); i++) {
                pituus = i;
                
            }
            dm.addElement("Teksti1, pituus: " + pituus);
            jtxtareaTulos.setModel(dm);
        }
        
        if(buttonGroup1.getSelection().getActionCommand()=="Suuri") {
            dm.addElement(teksti2.toUpperCase());
            jtxtareaTulos.setModel(dm);
        }
        
        if(buttonGroup1.getSelection().getActionCommand()=="Liite") {
            dm.addElement(teksti1.toLowerCase() + " " + teksti2.toUpperCase());
            jtxtareaTulos.setModel(dm);
        }
        
        if(buttonGroup1.getSelection().getActionCommand()=="K") {
            char t = teksti2.charAt(0);  
            if(t == 'K') {
                String lause = "Kyllä";
                dm.addElement(lause);  
            }else{
                dm.addElement("Ei");  
            }
            jtxtareaTulos.setModel(dm);
        }
        
        if(buttonGroup1.getSelection().getActionCommand()=="Korvaus") {  
            String t = jtxt1.getText();
            String vaikea = "vaikea";
            dm.addElement(t.replace("vaikea", "helppo"));
            jtxtareaTulos.setModel(dm);
        }   
        
        if(buttonGroup1.getSelection().getActionCommand()=="Taulukko") {
            String t = new String(jtxt1.getText());
            String[] words = t.split(",");
            int i = 0;
            for(String word: words) {
                String sana = word + " : " + i;
                i++;
                dm.addElement(sana);
            }
            jtxtareaTulos.setModel((dm));

        }          
    }//GEN-LAST:event_jbtnAjaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Merkkijono1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Merkkijono1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Merkkijono1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Merkkijono1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Merkkijono1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnAja;
    private javax.swing.JRadioButton jrbtK;
    private javax.swing.JRadioButton jrbtKorvaus;
    private javax.swing.JRadioButton jrbtLiite;
    private javax.swing.JRadioButton jrbtPituus;
    private javax.swing.JRadioButton jrbtSuuri;
    private javax.swing.JRadioButton jrbtTaulukko;
    private javax.swing.JRadioButton jrbtVertaaminen;
    private javax.swing.JTextField jtxt1;
    private javax.swing.JTextField jtxt2;
    private javax.swing.JList<String> jtxtareaTulos;
    // End of variables declaration//GEN-END:variables
}
