/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.forsilmukka;

import javax.swing.DefaultListModel;

/**
 *
 * @author heyno
 */
public class FORsilmukka1 extends javax.swing.JFrame {

    /**
     * Creates new form FORsilmukka1
     */
    public FORsilmukka1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jlbl1 = new javax.swing.JLabel();
        jlblNimi = new javax.swing.JLabel();
        jlblIka = new javax.swing.JLabel();
        jtxtNimi = new javax.swing.JTextField();
        jtxtIka = new javax.swing.JTextField();
        jbtnTerve = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlstTervehdys = new javax.swing.JList<>();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(137, 9, 42));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jlbl1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        jlbl1.setText("Ole hyvä ja anna nimesi ja ikäsi vuosina.");

        jlblNimi.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jlblNimi.setText("Nimi:");

        jlblIka.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jlblIka.setText("Ikä:");

        jtxtNimi.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N

        jtxtIka.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N

        jbtnTerve.setBackground(new java.awt.Color(224, 158, 171));
        jbtnTerve.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jbtnTerve.setText("Tervehdys");
        jbtnTerve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTerveActionPerformed(evt);
            }
        });

        jlstTervehdys.setBackground(new java.awt.Color(183, 0, 48));
        jlstTervehdys.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jlstTervehdys.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jlstTervehdys);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbl1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblNimi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblIka, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtIka, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtNimi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnTerve))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jlbl1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNimi)
                    .addComponent(jtxtNimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblIka)
                    .addComponent(jtxtIka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jbtnTerve)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnTerveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTerveActionPerformed
        // TODO add your handling code here:
        int ika;
        String nimi;
        
        ika = Integer.parseInt(jtxtIka.getText());
        nimi = jtxtNimi.getText();
        
        
        DefaultListModel dlm = new DefaultListModel();
        for (int i=1; i<=ika; i++) {
            dlm.addElement("Hyvää syntymäpäivää: " + nimi + " " + i);
        }
        jlstTervehdys.setModel(dlm);
    }//GEN-LAST:event_jbtnTerveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORsilmukka1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORsilmukka1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORsilmukka1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORsilmukka1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORsilmukka1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton jbtnTerve;
    private javax.swing.JLabel jlbl1;
    private javax.swing.JLabel jlblIka;
    private javax.swing.JLabel jlblNimi;
    private javax.swing.JList<String> jlstTervehdys;
    private javax.swing.JTextField jtxtIka;
    private javax.swing.JTextField jtxtNimi;
    // End of variables declaration//GEN-END:variables
}
