/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pizzalaskuri;

/**
 *
 * @author heyno
 */
public class Pizzalaskuri1 extends javax.swing.JFrame {

    /**
     * Creates new form Pizzalaskuri1
     */
    public Pizzalaskuri1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioNormaali = new javax.swing.JRadioButton();
        jRadioPerhe = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jchkKinkku = new javax.swing.JCheckBox();
        jchkAnanas = new javax.swing.JCheckBox();
        jchkMeetwursti = new javax.swing.JCheckBox();
        jchkKana = new javax.swing.JCheckBox();
        jchkHerkkusieni = new javax.swing.JCheckBox();
        jchkAurajuusto = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jtxtHinta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtMaara = new javax.swing.JTextField();
        jbtnTilaa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Pizzalaskuri");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Valitse koko, kappalemäärä ja täytteet, niin ohjelma laskee hinnan pizzalle.");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Koko");

        buttonGroup1.add(jRadioNormaali);
        jRadioNormaali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioNormaali.setText("Normaali 5 €");
        jRadioNormaali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioNormaaliActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioPerhe);
        jRadioPerhe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioPerhe.setText("Perhe 9 €");
        jRadioPerhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioPerheActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Täytteet");

        jchkKinkku.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jchkKinkku.setText("Kinkku + 0,75 €");
        jchkKinkku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkKinkkuActionPerformed(evt);
            }
        });

        jchkAnanas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jchkAnanas.setText("Ananas + 0,50 €");
        jchkAnanas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkAnanasActionPerformed(evt);
            }
        });

        jchkMeetwursti.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jchkMeetwursti.setText("Meetwursti + 0,50 €");
        jchkMeetwursti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkMeetwurstiActionPerformed(evt);
            }
        });

        jchkKana.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jchkKana.setText("Kana + 0,80 €");
        jchkKana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkKanaActionPerformed(evt);
            }
        });

        jchkHerkkusieni.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jchkHerkkusieni.setText("Herkkusieni + 0,50 €");
        jchkHerkkusieni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkHerkkusieniActionPerformed(evt);
            }
        });

        jchkAurajuusto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jchkAurajuusto.setText("Aurajuusto + 0,50 €");
        jchkAurajuusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkAurajuustoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Hinta");

        jtxtHinta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtHintaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Määrä");

        jtxtMaara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMaaraActionPerformed(evt);
            }
        });

        jbtnTilaa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnTilaa.setText("Tilaa");
        jbtnTilaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTilaaActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Normaali ja perhepizzanhintaan kuuluu pohja, tomaattikastike ja juusto.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnTilaa)
                            .addComponent(jRadioPerhe, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioNormaali, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jchkAurajuusto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jchkHerkkusieni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                .addComponent(jchkKana, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jchkMeetwursti, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jchkAnanas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jchkKinkku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtHinta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtxtMaara, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jRadioNormaali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioPerhe)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jchkKinkku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchkAnanas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchkMeetwursti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchkKana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchkHerkkusieni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jchkAurajuusto)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtHinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtMaara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtnTilaa)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnTilaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTilaaActionPerformed
        // TODO add your handling code here:
      double total;  
      double hinta = Double.parseDouble(jtxtHinta.getText());
      int maara = Integer.parseInt(jtxtMaara.getText()); 
      
      total = hinta * maara;
      String tot = String.format("%.2f", total);
      String appendText = ("Loppusumma: " + "\n" + tot + " €");
      jTextArea1.append(appendText);
      
     
                
    }//GEN-LAST:event_jbtnTilaaActionPerformed

    private void jtxtHintaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtHintaActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jtxtHintaActionPerformed

    private void jRadioNormaaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioNormaaliActionPerformed
        // TODO add your handling code here:
        
        double hinta=5;
        jtxtHinta.setText(String.valueOf(hinta));
        
                if(jchkKinkku.isSelected()) {
                    hinta += 0.75;
                    jtxtHinta.setText(String.valueOf(hinta)); 
                }
            
                else if(jchkAnanas.isSelected()){
                    hinta += 0.50; 
                    jtxtHinta.setText(String.valueOf(hinta));                     
                }
                
                else if(jchkMeetwursti.isSelected()){
                    hinta += 0.50; 
                    jtxtHinta.setText(String.valueOf(hinta));                     
                }

                else if(jchkKana.isSelected()){
                    hinta += 0.80; 
                    jtxtHinta.setText(String.valueOf(hinta));                     
                }

                else if(jchkHerkkusieni.isSelected()){
                    hinta += 0.50; 
                    jtxtHinta.setText(String.valueOf(hinta));                     
                }

                else if(jchkAurajuusto.isSelected()){
                    hinta += 0.50; 
                    jtxtHinta.setText(String.valueOf(hinta));                     
                }             
        
                jtxtHinta.setText(String.valueOf(hinta)); 
    }//GEN-LAST:event_jRadioNormaaliActionPerformed

    private void jRadioPerheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioPerheActionPerformed
        // TODO add your handling code here:
        
        double hinta=9;
        jtxtHinta.setText(String.valueOf(hinta));
        
                if(jchkKinkku.isSelected()) {
                    hinta += 0.75;
                    jtxtHinta.setText(String.valueOf(hinta)); 
                }
            
                else if(jchkAnanas.isSelected()){
                    hinta += 0.50; 
                    jtxtHinta.setText(String.valueOf(hinta));                     
                }
                
                else if(jchkMeetwursti.isSelected()){
                    hinta += 0.50; 
                    jtxtHinta.setText(String.valueOf(hinta));                     
                }

                else if(jchkKana.isSelected()){
                    hinta += 0.80; 
                    jtxtHinta.setText(String.valueOf(hinta));                     
                }

                else if(jchkHerkkusieni.isSelected()){
                    hinta += 0.50; 
                    jtxtHinta.setText(String.valueOf(hinta));                     
                }

                else if(jchkAurajuusto.isSelected()){
                    hinta += 0.50; 
                    jtxtHinta.setText(String.valueOf(hinta));                     
                }             
        
                jtxtHinta.setText(String.valueOf(hinta));         
    }//GEN-LAST:event_jRadioPerheActionPerformed

    private void jchkKinkkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkKinkkuActionPerformed
        // TODO add your handling code here:
            float hinta = Float.parseFloat(jtxtHinta.getText());
                if(jchkKinkku.isSelected()) {
                    hinta += 0.7;
                    jtxtHinta.setText(String.valueOf(hinta));                    
                } else {
                    hinta -= 0.7 ;
                    jtxtHinta.setText(String.valueOf(hinta));                     
                }
                
                                 
        
    }//GEN-LAST:event_jchkKinkkuActionPerformed

    private void jchkAnanasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkAnanasActionPerformed
        // TODO add your handling code here:
        double hinta = Double.parseDouble(jtxtHinta.getText());
        
                if(jchkAnanas.isSelected()){
                    hinta += 0.50; 
                    jtxtHinta.setText(String.valueOf(hinta));                     
                } else {
                    hinta -= 0.50;
                    jtxtHinta.setText(String.valueOf(hinta));                     
                }
                        
        
    }//GEN-LAST:event_jchkAnanasActionPerformed

    private void jchkMeetwurstiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkMeetwurstiActionPerformed
        // TODO add your handling code here:
        
        double hinta = Double.parseDouble(jtxtHinta.getText());
        
                if(jchkMeetwursti.isSelected()){
                    hinta += 0.50; 
                    jtxtHinta.setText(String.valueOf(hinta));                     
                } else {
                    hinta -= 0.50;
                    jtxtHinta.setText(String.valueOf(hinta));                     
                }
                         
    }//GEN-LAST:event_jchkMeetwurstiActionPerformed

    private void jchkKanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkKanaActionPerformed
        // TODO add your handling code here:
        
        double hinta = Double.parseDouble(jtxtHinta.getText());
                if(jchkKana.isSelected()){
                    hinta += 0.80; 
                    jtxtHinta.setText(String.valueOf(hinta));                     
                } else {
                    hinta -= 0.80;
                    jtxtHinta.setText(String.valueOf(hinta));                     
                }                
                
    }//GEN-LAST:event_jchkKanaActionPerformed

    private void jchkHerkkusieniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkHerkkusieniActionPerformed
        // TODO add your handling code here:
        
        double hinta = Double.parseDouble(jtxtHinta.getText());
                
                if(jchkHerkkusieni.isSelected()){
                    hinta += 0.50; 
                    jtxtHinta.setText(String.valueOf(hinta));                     
                } else {
                    hinta -= 0.50;
                    jtxtHinta.setText(String.valueOf(hinta));                     
                }


        
    }//GEN-LAST:event_jchkHerkkusieniActionPerformed

    private void jchkAurajuustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkAurajuustoActionPerformed
        // TODO add your handling code here:
        double hinta = Double.parseDouble(jtxtHinta.getText());
                
                if(jchkAurajuusto.isSelected()){
                    hinta += 0.50; 
                    jtxtHinta.setText(String.valueOf(hinta));                     
                } else {
                    hinta -= 0.50;
                    jtxtHinta.setText(String.valueOf(hinta));                     
                }          
        
    }//GEN-LAST:event_jchkAurajuustoActionPerformed

    private void jtxtMaaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMaaraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMaaraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pizzalaskuri1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pizzalaskuri1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pizzalaskuri1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pizzalaskuri1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pizzalaskuri1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioNormaali;
    private javax.swing.JRadioButton jRadioPerhe;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbtnTilaa;
    private javax.swing.JCheckBox jchkAnanas;
    private javax.swing.JCheckBox jchkAurajuusto;
    private javax.swing.JCheckBox jchkHerkkusieni;
    private javax.swing.JCheckBox jchkKana;
    private javax.swing.JCheckBox jchkKinkku;
    private javax.swing.JCheckBox jchkMeetwursti;
    private javax.swing.JTextField jtxtHinta;
    private javax.swing.JTextField jtxtMaara;
    // End of variables declaration//GEN-END:variables
}
